In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv('diabetes_dataset.csv')

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.shape

(768, 9)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
zero_not_accepted = df.columns

In [7]:
zero_not_accepted[0:8]

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age'],
      dtype='object')

In [8]:
for column in zero_not_accepted[0:8]:
    df[column] = df[column].replace(0,np.NaN)
    mean = int(df[column].mean(skipna=True))
    df[column] = df[column].replace(np.NaN,mean)

In [9]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          6.0    148.0           72.0           35.0    155.0  33.6   
1          1.0     85.0           66.0           29.0    155.0  26.6   
2          8.0    183.0           64.0           29.0    155.0  23.3   
3          1.0     89.0           66.0           23.0     94.0  28.1   
4          4.0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [10]:
#Installing the library 
#!pip install sweetviz
#Importing the library 
import sweetviz as sv
report = sv.analyze(df)
report.show_html()

                                             |          | [  0%]   00:00 -> (? left)

Report SWEETVIZ_REPORT.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.


In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X = df.iloc[:,0:8]
y = df.iloc[:,8]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=101,stratify=y)

In [14]:
from sklearn.naive_bayes import MultinomialNB

In [15]:
mm = MultinomialNB()

In [16]:
mm.fit(X_train, y_train)

MultinomialNB()

In [17]:
y_pred = mm.predict(X_test)

In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[108,  42],
       [ 62,  19]], dtype=int64)

In [20]:
from sklearn.metrics import accuracy_score
print('Multinomial Accuracy = ', accuracy_score(y_test,y_pred))

Multinomial Accuracy =  0.5497835497835498


In [21]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.64      0.72      0.67       150
           1       0.31      0.23      0.27        81

    accuracy                           0.55       231
   macro avg       0.47      0.48      0.47       231
weighted avg       0.52      0.55      0.53       231



In [22]:
from sklearn.naive_bayes import BernoulliNB

In [23]:
bm = BernoulliNB()

In [24]:
bm.fit(X_train,y_train)

BernoulliNB()

In [25]:
y_pred = bm.predict(X_test)

In [26]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[150,   0],
       [ 81,   0]], dtype=int64)

In [27]:
from sklearn.metrics import accuracy_score
print('Bernoulli Accuracy = ', accuracy_score(y_test,y_pred))

Bernoulli Accuracy =  0.6493506493506493


In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.65      1.00      0.79       150
           1       0.00      0.00      0.00        81

    accuracy                           0.65       231
   macro avg       0.32      0.50      0.39       231
weighted avg       0.42      0.65      0.51       231



C:\Users\Harshal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Harshal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Harshal\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
from sklearn.naive_bayes import GaussianNB

In [30]:
gm = GaussianNB()

In [31]:
gm.fit(X_train,y_train)

GaussianNB()

In [32]:
y_pred = gm.predict(X_test)

In [33]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[125,  25],
       [ 38,  43]], dtype=int64)

In [34]:
from sklearn.metrics import accuracy_score
print('Gaussian Accuracy = ', accuracy_score(y_test,y_pred))

Gaussian Accuracy =  0.7272727272727273


In [35]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.77      0.83      0.80       150
           1       0.63      0.53      0.58        81

    accuracy                           0.73       231
   macro avg       0.70      0.68      0.69       231
weighted avg       0.72      0.73      0.72       231

